services:
  # Spring Boot App Service
  spring-boot-app:
    container_name: spring-boot-app-container
    image: rest-api-mysql:1.0
    ports:
      - "8085:8085"
    depends_on:
      - db
    volumes:
      - my-volume:/data

  # MySQL Service
  db:
    container_name: mysql-container
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=agendaescolar
    volumes:
      - my-volume:/var/lib/mysql

volumes:
  my-volume:
